const slides = [
  {
    title: "Peter Thomas Roth",
    image: "https://www.sephora.com/productimages/sku/s2165512-main-zoom.jpg?imwidth=166",
    points: "100 points",
    description: "Water Drench",
    shortDescription: "Hydrating serum for all skin types.",
    type: "Skincare",
    category: "Makeup",
  },
  {
    title: "Murad",
    image: "https://www.sephora.com/productimages/sku/s2470904-main-zoom.jpg?imwidth=122",
    points: "100 points",
    description: "Clarifying .",
    shortDescription: "Oil-free moisturizer for skin.",
    type: "Skincare",
    category: "Makeup",
  },
  {
    title: "Youth",
    image: "https://www.sephora.com/productimages/sku/s2580520-main-zoom.jpg?pb=clean-at-sephora&imwidth=122",
    points: "100 points",
    description: "Superfood Air-Whip...",
    shortDescription: "Lightweight cream ",
    type: "Skincare",
    category: "Makeup",
  },
  {
    title: "Benefit Cosmetics",
    image: "https://www.sephora.com/productimages/sku/s2635886-main-zoom.jpg?imwidth=122",
    points: "100 points",
    description: "BADgal BANG! ",
    shortDescription: "Volumizing mascara ",
    type: "Makeup",
    category: "Makeup",
  },
  {
    title: "Estée Lauder",
    image: "https://www.sephora.com/productimages/sku/s2659233-main-zoom.jpg?imwidth=122",
    points: "100 points",
    description: "Advanced Night...",
    shortDescription: "Night serum for anti-aging",
    type: "Skincare",
    category: "Makeup",
  },
  {
    title: "CLINIQUE",
    image: "https://www.sephora.com/productimages/sku/s2696557-main-zoom.jpg?imwidth=122",
    points: "100 points",
    description: "High Impact™ Easy...",
    shortDescription: "Gentle mascara for sensitive eyes.",
    type: "Makeup",
    category: "Makeup",
  },
  {
    title: "JVN",
    image: "https://www.sephora.com/productimages/sku/s2771202-main-zoom.jpg?pb=clean-planet-aware&imwidth=122",
    points: "100 points",
    description: "Complete Pre-Wash...",
    shortDescription: "Pre-wash hair treatment",
    type: "Haircare",
    category: "Makeup",
  },
  {
    title: "Living Proof",
    image: "https://www.sephora.com/productimages/sku/s2782464-main-zoom.jpg?pb=clean-at-sephora&imwidth=122",
    points: "100 points",
    description: "Clarifying Shampoo...",
    shortDescription: "Deep cleansing shampoo ",
    type: "Haircare",
    category: "Makeup",
  },
  {
    title: "BondiBoost",
    image: "https://www.sephora.com/productimages/sku/s2165512-main-zoom.jpg?imwidth=166",
    points: "100 points",
    description: "Miracle Hair Mask...",
    shortDescription: "Repairing hair mask ",
    type: "Haircare",
    category: "Makeup",
  },
  {
    title: "Anastasia",
    image: "https://www.sephora.com/productimages/sku/s2165512-main-zoom.jpg?imwidth=166",
    points: "100 points",
    description: "Brow Wiz® Ultra-Sli...",
    shortDescription: "Precision eyebrow pencil.",
    type: "Makeup",
    category: "Makeup",
  },
  {
    title: "Too Faced",
    image: "https://www.sephora.com/productimages/sku/s2802676-main-zoom.jpg?imwidth=166",
    points: "100 points",
    description: "Better Than Sex...",
    shortDescription: "Iconic mascara for volume and length.",
    type: "Makeup",
    category: "Makeup",
  },
  {
    title: "Tower 28 Beauty",
    image: "https://www.sephora.com/productimages/sku/s2786978-main-zoom.jpg?imwidth=122",
    points: "100 points",
    description: "SOS Daily Skin...",
    shortDescription: "Soothing spray for irritated skin.",
    type: "Skincare",
    category: "Makeup",
  },
  {
    title: "Peter Thomas Roth",
    image: "https://www.sephora.com/productimages/sku/s2786986-main-zoom.jpg?imwidth=122",
    points: "100 points",
    description: "Peptide Skinjection...",
    shortDescription: "Peptide serum for firm skin.",
    type: "Skincare",
    category: "Makeup",
  },
  {
    title: "fresh",
    image: "https://www.sephora.com/productimages/sku/s2788669-main-zoom.jpg?imwidth=122",
    points: "100 points",
    description: "Soy Hydrating G...",
    shortDescription: "Gentle gel cleanser for all skin types.",
    type: "Skincare",
    category: "Makeup",
  },
  {
    title: "Glow Recipe",
    image: "https://www.sephora.com/productimages/sku/s2450815-main-zoom.jpg?imwidth=122",
    points: "250 points",
    description: "Stellar Skincare Duo",
    shortDescription: "Skincare duo for glowing skin.",
    type: "Skincare",
    category: "Makeup",
  },
];

export default slides;
