const slides = [
  {
    title: "belif",
    image: "https://www.sephora.com/productimages/sku/s2802163-main-zoom.jpg?imwidth=166",
    price: "$32.00",
    description: "Aqua Bomb Depu...",
    shortDescription: "Moisturizing gel cream for a refreshing boost.",
    category: "Skincare",
  },
  {
    title: "Kiehl's Since 1851",
    image: "https://www.sephora.com/productimages/sku/s2814325-main-zoom.jpg?imwidth=166",
    price: "$52.00",
    description: "Auto-Tone Skin..",
    shortDescription: "Skin tone correction for, even complexion.",
    category: "Skincare",
  },
  {
    title: "Paula's Choice",
    image: "https://www.sephora.com/productimages/sku/s2810539-main-zoom.jpg?imwidth=166",
    price: "$68.00",
    description: "Clinical PRO Rent...",
    shortDescription: "Resurfacing treatment for younger skin.",
    category: "Skincare",
  },
  {
    title: "Glow Recipe",
    image: "https://www.sephora.com/productimages/sku/s2802387-main-zoom.jpg?imwidth=166",
    price: "$29.00",
    description: "Watermelon Glow...",
    shortDescription: "Hydrating mask for a glowing complexion.",
    category: "Skincare",
  },
  {
    title: "Shani Darden skin...",
    image: "https://www.sephora.com/productimages/sku/s2811628-main-zoom.jpg?imwidth=166",
    price: "$39.00",
    description: "Mini Triple Acid...",
    shortDescription: "Mini facial exfoliation for brighten skin",
    category: "Skincare",
  },
  {
    title: "Kosas Bluefly",
    image: "https://www.sephora.com/productimages/sku/s2795060-main-zoom.jpg?imwidth=122",
    price: "$24.00",
    description: "Soulgaze",
    shortDescription: "Soft matte lipstick for a natural look.",
    category: "Skincare",
  },
  {
    title: "Summer Fridays",
    image: "https://www.sephora.com/productimages/sku/s2744696-main-zoom.jpg?imwidth=122",
    price: "$26.00",
    description: "Dream Lip Oil",
    shortDescription: "Nourishing lip oil with a soothing effect.",
    category: "Skincare",
  },
  {
    title: "OLEHENRIKSEN",
    image: "https://www.sephora.com/productimages/sku/s2648467-main-zoom.jpg?imwidth=122",
    price: "$22.00",
    description: "Pout Preserve",
    shortDescription: "Hydrating lip treatment for shiny lips.",
    category: "Skincare",
  },
  {
    title: "BLUEFLY ",
    image: "https://www.sephora.com/productimages/sku/s2759959-main-zoom.jpg?imwidth=122",
    price: "$20.00",
    description: "Hydrating Cica  ",
    shortDescription: "Soothing skincare for sensitive skin",
    category: "Skincare",
  },
  {
    title: "PHLUR",
    image: "https://www.sephora.com/productimages/sku/s2766186-main-zoom.jpg?imwidth=122",
    price: "$45.00",
    description: "Missing Person Bod...",
    shortDescription: "Body fragrance for a fresh.",
    category: "Skincare",
  },
];

export default slides;
